name: Update Images

on:
  push:
    branches: [ main ]
    paths:
      - 'image/**'

  workflow_dispatch:

jobs:
  update:
    name: Update Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update images
        run: |
          python generate_img_list.py


      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: ':wrench: 自动更新图库列表'
          add: |
            'abscension_img_list.json'
