name: Update Resources

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'

  workflow_dispatch:

jobs:
  update:
    name: Update Resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Update resources
        run: |
          python generate_data_list.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: ':wrench: 自动更新资源列表'
          add: |
            'abscension_data_list.json'
            'resources.zip'
